version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
    restart: always
    container_name: app-training-provisioner
    build:
      context: .
      target: app-container
    volumes:
      - ./training_provisioner:/app/training_provisioner
    ports:
      - "8000:8000"
      - "8001:8001"
