ingress:
  enabled: true
  tls:
    studenttraining:
      secretName: test-apps.studenttraining.uw.edu-ingress-cert
      hosts:
        - test-apps.studenttraining.uw.edu
  hosts:
    studenttraining:
      host: test-apps.studenttraining.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: false

resources:
  limits:
    cpu: 700m
    memory: 1.0Gi
  requests:
    cpu: 250m
    memory: 500Mi

externalService:
  enabled: true
  name: studenttraining-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.43
  servicePort: 5432
database:
  engine: postgres
  name: studenttraining_provisioner_test
  hostname: studenttraining-db-service
  secretName: test-apps.studenttraining.uw.edu-sql-secrets

repo: studenttraining
instance: test
namespace:
  enabled: true

sidecarContainers:
  forwarder:
    image: "us-docker.pkg.dev/uwit-mci-axdd/containers/uw-ssh-client:89695b2"
    environmentVariables:
      - name: PROXY_ID_KEY
        valueFrom:
          secretKeyRef:
            name: test-apps.studenttraining.uw.edu-shared-secrets
            key: proxy-id-key
      - name: PROXY_ID
        valueFrom:
          secretKeyRef:
            name: test-apps.studenttraining.uw.edu-shared-secrets
            key: proxy-id
      - name: PROXY_HOSTNAME
        valueFrom:
          secretKeyRef:
            name: test-apps.studenttraining.uw.edu-shared-secrets
            key: proxy-hostname
      - name: TARGET_HOSTNAME
        valueFrom:
          secretKeyRef:
            name: test-apps.studenttraining.uw.edu-edw-secrets
            key: hostname
      - name: TARGET_PORT
        value: "1433"
      - name: LOCAL_PORT
        value: "1433"
    command:
      - "sh"
      - "-c"
      - 'mkdir -m 0700 ~/.ssh && echo "${PROXY_ID_KEY}" > ~/.ssh/id_ecdsa && chmod 400 ~/.ssh/id_ecdsa && ssh ${PROXY_ID}@${PROXY_HOSTNAME} -o StrictHostKeyChecking=no -N -L 127.0.0.1:${LOCAL_PORT}:${TARGET_HOSTNAME}:${TARGET_PORT}'

memcached:
  enabled: false
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate

gcsCredentials:
  mounted: true
  secretName: test-apps.studenttraining.uw.edu-gcs-credentials

cronjob:
  enabled: true
  jobs:
    - name: load-training-courses
      schedule: "40 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["load_training_courses"]
      resources:
        limits:
          cpu: 700m
          memory: 1.0Gi
        requests:
          cpu: 250m
          memory: 500Mi
      sidecars:
        - name: ssh-proxy
          image: "us-docker.pkg.dev/uwit-mci-axdd/containers/uw-ssh-client:89695b2"
          environmentVariables:
            - name: PROXY_ID_KEY
              valueFrom:
                secretKeyRef:
                  name: test-apps.studenttraining.uw.edu-shared-secrets
                  key: proxy-id-key
            - name: PROXY_ID
              valueFrom:
                secretKeyRef:
                  name: test-apps.studenttraining.uw.edu-shared-secrets
                  key: proxy-id
            - name: PROXY_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: test-apps.studenttraining.uw.edu-shared-secrets
                  key: proxy-hostname
            - name: TARGET_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: test-apps.studenttraining.uw.edu-edw-secrets
                  key: hostname
            - name: TARGET_PORT
              value: "1433"
            - name: LOCAL_PORT
              value: "1433"
          command:
            - "sh"
            - "-c"
            - 'mkdir -m 0700 ~/.ssh && echo "${PROXY_ID_KEY}" > ~/.ssh/id_ecdsa && chmod 400 ~/.ssh/id_ecdsa && ssh ${PROXY_ID}@${PROXY_HOSTNAME} -o StrictHostKeyChecking=no -N -L 127.0.0.1:${LOCAL_PORT}:${TARGET_HOSTNAME}:${TARGET_PORT}'
    - name: import-training-courses
      schedule: "40 9 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["import_training_courses"]

daemon:
  enabled: true
  daemons:
    - name: monitor-imports
      replicaCount: 1
      command: ["/scripts/management_daemon.sh"]
      args: ["--delay", "30", "monitor_imports"]

certs:
  mounted: true
  certPath: /certs/test-apps.studenttraining.uw.edu-ic.cert
  keyPath: /certs/test-apps.studenttraining.uw.edu-ic.key
  secretName: test-apps.studenttraining.uw.edu-ic-certs

mountedSecrets:
  enabled: true
  secretName: test-apps.studenttraining.uw.edu-secrets
  mountPath: /app/training_provisioner/data
  items:
    - key: membership.json
      path: membership.json

environmentVariables:
  - name: ENV
    value: test

  - name: STUDENTTRAINING_ACCOUNT_DOMAIN
    value: uwstudenttraining.test.instructure.com
  - name: CANVAS_ACCOUNT_DOMAIN
    value: uw.test.instructure.com

  - name: CANVAS_ENV
    value: EVAL
  - name: CANVAS_TIMEOUT
    value: "20"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test-apps.studenttraining.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: test-apps.studenttraining.uw.edu

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test-apps.studenttraining.uw.edu-secrets
    secretKey: django-secret
  studenttrainingAccountID:
    name: CANVAS_ACCOUNT_ID
    secretName: test-apps.studenttraining.uw.edu-shared-secrets
    secretKey: studenttraining-account-id
  studenttrainingAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: test-apps.studenttraining.uw.edu-shared-secrets
    secretKey: studenttraining-api-token
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: test-apps.studenttraining.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: test-apps.studenttraining.uw.edu-shared-secrets
    secretKey: storage-project-id
  samlSPCert:
    name: SP_CERT
    secretName: test-apps.studenttraining.uw.edu-ic-certs
    secretKey: test-apps.studenttraining.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test-apps.studenttraining.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
  EDWuser:
    name: EDW_USER
    secretName: test-apps.studenttraining.uw.edu-edw-secrets
    secretKey: username
  EDWpassword:
    name: EDW_PASS
    secretName: test-apps.studenttraining.uw.edu-edw-secrets
    secretKey: password

externalSecrets:
  enabled: true
  secrets:
    - name: test-apps.studenttraining.uw.edu-shared-secrets
      externalKey: studenttraining/shared/secrets
      data:
        - name: storage-project-id
          property: storage-project-id
        - name: studenttraining-account-id
          property: studenttraining-account-id
        - name: studenttraining-api-token
          property: studenttraining-api-token
        - name: proxy-id-key
          property: proxy-id-key
        - name: proxy-id
          property: proxy-id
        - name: proxy-hostname
          property: proxy-hostname
    - name: test-apps.studenttraining.uw.edu-gcs-credentials
      externalKey: studenttraining/shared/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: test-apps.studenttraining.uw.edu-secrets
      externalKey: studenttraining/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: storage-bucket-name
          property: storage-bucket-name
        - name: membership.json
          property: membership.json
    - name: test-apps.studenttraining.uw.edu-sql-secrets
      externalKey: studenttraining/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test-apps.studenttraining.uw.edu-edw-secrets
      externalKey: studenttraining/shared/edw-secrets
      data:
        - name: hostname
          property: hostname
        - name: username
          property: username
        - name: password
          property: password
    - name: test-apps.studenttraining.uw.edu-ic-certs
      externalKey: studenttraining/test/ic-certs
      data:
        - name: test-apps.studenttraining.uw.edu-ic.cert
          property: test-apps.studenttraining.uw.edu-ic.cert
        - name: test-apps.studenttraining.uw.edu-ic.key
          property: test-apps.studenttraining.uw.edu-ic.key
    - name: test-apps.studenttraining.uw.edu-uw-idp-cert
      externalKey: idp-cert
      data:
        - name: uw-idp-cert
          property: cert
